// <auto-generated />
using BulkyWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BulkyWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260212062356_Seed")]
    partial class Seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BulkyWeb.Models.Category", b =>
                {
                    b.Property<int>("Category_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Category_Id"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.HasKey("Category_Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Category_Id = 1,
                            CategoryName = "Action",
                            DisplayOrder = 1
                        },
                        new
                        {
                            Category_Id = 2,
                            CategoryName = "Adventure",
                            DisplayOrder = 2
                        },
                        new
                        {
                            Category_Id = 3,
                            CategoryName = "Biography",
                            DisplayOrder = 3
                        },
                        new
                        {
                            Category_Id = 4,
                            CategoryName = "Business",
                            DisplayOrder = 4
                        },
                        new
                        {
                            Category_Id = 5,
                            CategoryName = "Classic",
                            DisplayOrder = 5
                        },
                        new
                        {
                            Category_Id = 6,
                            CategoryName = "Drama",
                            DisplayOrder = 6
                        },
                        new
                        {
                            Category_Id = 7,
                            CategoryName = "Fantasy",
                            DisplayOrder = 7
                        },
                        new
                        {
                            Category_Id = 8,
                            CategoryName = "History",
                            DisplayOrder = 8
                        },
                        new
                        {
                            Category_Id = 9,
                            CategoryName = "Science",
                            DisplayOrder = 9
                        },
                        new
                        {
                            Category_Id = 10,
                            CategoryName = "Technology",
                            DisplayOrder = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
