// <auto-generated />
using BulkyWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BulkyWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260224175411_addImageURLForProduct")]
    partial class addImageURLForProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BulkyWeb.Models.Category", b =>
                {
                    b.Property<int>("Category_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Category_Id"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.HasKey("Category_Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Category_Id = 1,
                            CategoryName = "Action",
                            DisplayOrder = 1
                        },
                        new
                        {
                            Category_Id = 2,
                            CategoryName = "Adventure",
                            DisplayOrder = 2
                        },
                        new
                        {
                            Category_Id = 3,
                            CategoryName = "Biography",
                            DisplayOrder = 3
                        },
                        new
                        {
                            Category_Id = 4,
                            CategoryName = "Business",
                            DisplayOrder = 4
                        },
                        new
                        {
                            Category_Id = 5,
                            CategoryName = "Classic",
                            DisplayOrder = 5
                        },
                        new
                        {
                            Category_Id = 6,
                            CategoryName = "Drama",
                            DisplayOrder = 6
                        },
                        new
                        {
                            Category_Id = 7,
                            CategoryName = "Fantasy",
                            DisplayOrder = 7
                        },
                        new
                        {
                            Category_Id = 8,
                            CategoryName = "History",
                            DisplayOrder = 8
                        },
                        new
                        {
                            Category_Id = 9,
                            CategoryName = "Science",
                            DisplayOrder = 9
                        },
                        new
                        {
                            Category_Id = 10,
                            CategoryName = "Technology",
                            DisplayOrder = 10
                        });
                });

            modelBuilder.Entity("BulkyWeb.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Category_Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Category_Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Ron Parker",
                            Category_Id = 9,
                            Description = "Horror",
                            ISBN = "FOT000000001",
                            ListPrice = 45.0,
                            Price = 40.0,
                            Price100 = 35.0,
                            Price50 = 38.0,
                            Title = "Shadows of Fear"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Emily Stone",
                            Category_Id = 3,
                            Description = "Psychological Thriller",
                            ISBN = "FOT000000002",
                            ListPrice = 30.0,
                            Price = 28.0,
                            Price100 = 24.0,
                            Price50 = 26.0,
                            Title = "The Silent Mind"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Michael Reeves",
                            Category_Id = 5,
                            Description = "Science Fiction",
                            ISBN = "FOT000000003",
                            ListPrice = 50.0,
                            Price = 47.0,
                            Price100 = 42.0,
                            Price50 = 45.0,
                            Title = "Code of Destiny"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Sophia Miller",
                            Category_Id = 7,
                            Description = "Mystery",
                            ISBN = "FOT000000004",
                            ListPrice = 35.0,
                            Price = 32.0,
                            Price100 = 27.0,
                            Price50 = 30.0,
                            Title = "Whispers in the Dark"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Liam Anderson",
                            Category_Id = 1,
                            Description = "Fantasy",
                            ISBN = "FOT000000005",
                            ListPrice = 48.0,
                            Price = 44.0,
                            Price100 = 39.0,
                            Price50 = 42.0,
                            Title = "Broken Kingdom"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Olivia Brown",
                            Category_Id = 7,
                            Description = "Adventure",
                            ISBN = "FOT000000006",
                            ListPrice = 28.0,
                            Price = 25.0,
                            Price100 = 20.0,
                            Price50 = 23.0,
                            Title = "Beyond the Horizon"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Daniel Cooper",
                            Category_Id = 2,
                            Description = "Drama",
                            ISBN = "FOT000000007",
                            ListPrice = 40.0,
                            Price = 36.0,
                            Price100 = 31.0,
                            Price50 = 34.0,
                            Title = "Fragments of Truth"
                        });
                });

            modelBuilder.Entity("BulkyWeb.Models.Product", b =>
                {
                    b.HasOne("BulkyWeb.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("Category_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
